### ISSUE TITLE
I have installed freesurfer_surface.  Because i Open lh.white with Notepad to display garbled characters how to read lh.white?

### ISSUE THREAD

**Issue by tanjia123456** [fphammerle/freesurfer-surface#20]
input:
from freesurfer_surface import Surface, Vertex, Triangle
surface = Surface.read_triangular('HLN-12-1.white')
print(surface)

output:
D:\anaconda3.4\python.exe D:/my_subject/test/read_.white.py
<freesurfer_surface.Surface object at 0x000002279D3DAAC8>

Process finished with exit code 0

**Comment by fphammerle** [comment]
Hi,

Could you try running the following code?

```python
from freesurfer_surface import Surface
surface = Surface.read_triangular('HLN-12-1.white')
print(surface.vertices)
print(surface.triangles)
```

Then you should see all the vertex and triangle information stored in `HLN-12-1.white`

**Comment by tanjia123456** [comment]
> ```python
> from freesurfer_surface import Surface
> surface = Surface.read_triangular('HLN-12-1.white')
> print(surface.vertices)
> print(surface.triangles)
> ```

thank you very much.  I can read the information !!!

**Comment by tanjia123456** [comment]
> 
> 
> > ```python
> > from freesurfer_surface import Surface
> > surface = Surface.read_triangular('HLN-12-1.white')
> > print(surface.vertices)
> > print(surface.triangles)
> > ```
> 
> thank you very much. I can read the information !!!

maybe I also need the vertices index,  the output such as:
1   1.0 2.0 3.0
2   2.0 3.0 4.0
3   3.0 4.0 5.0

**Comment by fphammerle** [comment]
> maybe I also need the vertices index, the output such as:
> 1 1.0 2.0 3.0
> 2 2.0 3.0 4.0
> 3 3.0 4.0 5.0

Could you try to run this example? 

```python
from freesurfer_surface import Surface

surface = Surface.read_triangular('HLN-12-1.white')

for triangle_index, triangle in enumerate(surface.triangles):
    print(triangle_index, triangle.vertex_indices[0],  triangle.vertex_indices[1],  triangle.vertex_indices[2])
```

**Comment by tanjia123456** [comment]
> 
> 
> > maybe I also need the vertices index, the output such as:
> > 1 1.0 2.0 3.0
> > 2 2.0 3.0 4.0
> > 3 3.0 4.0 5.0
> 
> Could you try to run this example?
> 
> ```python
> from freesurfer_surface import Surface
> 
> surface = Surface.read_triangular('HLN-12-1.white')
> 
> for triangle_index, triangle in enumerate(surface.triangles):
>     print(triangle_index, triangle.vertex_indices[0],  triangle.vertex_indices[1],  triangle.vertex_indices[2])
> ```
I tried it. this function is to get the nth triangle and its three vertices_indices?  
  
if I want get the  vertex index and vertex index_coordinate, suxh  as first vertex index, first vertex index_coordinate  :   
0: (22.812583923339844, -105.5467529296875, -23.141511917114258)


from freesurfer_surface import Surface
surface = Surface.read_triangular('HLN-12-1.white')
for vertices_index, vertices in enumerate(surface.vertices):
    print(vertices_index, vertices)

this code is right?

Is there a software to open the .white file directly？Not sure if the information extracted with freesurfer_surface is correct

**Comment by fphammerle** [comment]
> > ```python
> > from freesurfer_surface import Surface
> > 
> > surface = Surface.read_triangular('HLN-12-1.white')
> > 
> > for triangle_index, triangle in enumerate(surface.triangles):
> >     print(triangle_index, triangle.vertex_indices[0],  triangle.vertex_indices[1],  triangle.vertex_indices[2])
> > ```
> 
> I tried it. this function is to get the nth triangle and its three vertices_indices?

Yes, this code will dump the index of each triangle followed its 3 vertex indices.

> if I want get the vertex index and vertex index_coordinate, suxh as first vertex index, first vertex index_coordinate :
> 0: (22.812583923339844, -105.5467529296875, -23.141511917114258)
> 
> from freesurfer_surface import Surface
> surface = Surface.read_triangular('HLN-12-1.white')
> for vertices_index, vertices in enumerate(surface.vertices):
> print(vertices_index, vertices)
> 
> this code is right?

Yes, that's correct.
Your code will show the vertex index followed by its coordinates.

> Is there a software to open the .white file directly？Not sure if the information extracted with freesurfer_surface is correct
Unfortunately, I am not aware of any other software.
Maybe you could use freesurfer's `mris_convert` to convert the surface to a different format that's easier to read

**Comment by tanjia123456** [comment]
> 
> 
> > > ```python
> > > from freesurfer_surface import Surface
> > > 
> > > surface = Surface.read_triangular('HLN-12-1.white')
> > > 
> > > for triangle_index, triangle in enumerate(surface.triangles):
> > >     print(triangle_index, triangle.vertex_indices[0],  triangle.vertex_indices[1],  triangle.vertex_indices[2])
> > > ```
> > 
> > 
> > I tried it. this function is to get the nth triangle and its three vertices_indices?
> 
> Yes, this code will dump the index of each triangle followed its 3 vertex indices.
> 
> > if I want get the vertex index and vertex index_coordinate, suxh as first vertex index, first vertex index_coordinate :
> > 0: (22.812583923339844, -105.5467529296875, -23.141511917114258)
> > from freesurfer_surface import Surface
> > surface = Surface.read_triangular('HLN-12-1.white')
> > for vertices_index, vertices in enumerate(surface.vertices):
> > print(vertices_index, vertices)
> > this code is right?
> 
> Yes, that's correct.
> Your code will show the vertex index followed by its coordinates.
> 
> > Is there a software to open the .white file directly？Not sure if the information extracted with freesurfer_surface is correct
> 
> Unfortunately, I am not aware of any other software.
> 
> Maybe you could use freesurfer's `mris_convert` to convert the surface to a different format that's easier to read

I have two questions. 
（1）the index of each triangle followed its 3 vertex indices. why the triangle_index  not start from 0, but 235782？
your code output:                                                       
235782 119033 119032 118222
235783 118222 118223 119033
235784 119034 119033 118223
235785 118223 118232 119034
235786 119038 119034 118232
（2）the index of each vertices and it's coodinate. why the vertex_index  not start from 0? The information in the first line is incomplete？
my code output:
436981 28.09503555 34.1821022 ]
113578 [33.37352371 27.66130257 34.29809189]
113579 [32.54997253 27.83258057 34.50373077]
113580 [31.73606682 28.45427513 34.5328064 ]
113581 [27.15174675 28.3182621  34.66180038]

Is it possible that these two problems are caused by irregular file formats?

**Comment by fphammerle** [comment]
Both triangle and vertex index always start at 0.

I suspect that you python shell only shows the final items.

Try running:
```
from freesurfer_surface import Surface
surface = Surface.read_triangular('HLN-12-1.white')
for vertex_index, vertex in enumerate(surface.vertices[:5]):
    print(vertex_index, vertex)
```

then you'll get the first 5 vertices

You can adapt the number to get a different range

**Comment by fphammerle** [comment]
Yes,

> print(len(surface.vertices))

prints the number of vertices.

`[:len(surface.vertices)]` is equivalent to `[]`


Yes, the output is probably too long for your shell.

```
from freesurfer_surface import Surface
surface = Surface.read_triangular('HLN-12-1.white')
with open("vertices.txt", "w") as output_file:
    for vertex_index, vertex in enumerate(surface.vertices):
        output_file.write("{} {}\n".format(vertex_index, vertex))
```
writes the information to a file

**Comment by tanjia123456** [comment]
> from freesurfer_surface import Surface
> surface = Surface.read_triangular('HLN-12-1.white')
> with open("vertices.txt", "w") as output_file:
>     for vertex_index, vertex in enumerate(surface.vertices):
>         output_file.write("{} {}\n".format(vertex_index, vertex))

How can I thank you enough !   Have the opportunity to come to China to play, Chongqing eat hot pot

**Comment by fphammerle** [comment]
No problem, I'm glad it works for you :D

In case you have another question just open a new issue please
