### ISSUE TITLE
how to use  vertices and triangles to create a mesh?

### ISSUE THREAD

**Issue by tanjia123456** [fphammerle/freesurfer-surface#21]
rh.white has vertices and triangles,  I want to use these information to create a mesh. My subject is to segment the cerebral cortex. so what can i do to create a mesh? need any other information?

**Comment by fphammerle** [comment]
`Vertex` objects contain the coordinates:
```python
>>> surface.vertices[21]
Vertex(right=-4.846409320831299, anterior=-93.38225555419922, superior=-11.737957000732422)
>>> surface.vertices[21].anterior
-93.38225555419922
```

`Triangle` objects contain the indices of connecting vertices. The actual coordinates of a triangle's edges can be read using `surface.select_vertices`:
```python
>>> triangle = surface.triangles[42]
>>> triangle
Triangle(vertex_indices=(13, 69, 70))
>>> surface.select_vertices(triangle.vertex_indices)
[Vertex(right=-5.901014804840088, anterior=-93.37958526611328, superior=-9.877033233642578),
 Vertex(right=-6.758721351623535, anterior=-92.90492248535156, superior=-9.053672790527344),
 Vertex(right=-7.4223761558532715, anterior=-92.79309844970703, superior=-9.988789558410645)]
```

Does that help?

**Comment by tanjia123456** [comment]
> ```python
> surface.select_vertices(triangle.vertex_indices)
> ```

yes, I think I can try it. thank you!!!

**Comment by fphammerle** [comment]
I added some examples to the readme: https://github.com/fphammerle/freesurfer-surface/blob/f17897dfca2e9568177f1248e093d5976523b1f9/README.rst#read-surface-file
