### ISSUE TITLE
 ModuleNotFoundError: No module named 'freesurfer_surface.version;Hint: make sure your test modules/packages have valid Python names.

### ISSUE THREAD

**Issue by tanjia123456** [fphammerle/freesurfer-surface#22]
I'm sorry to bother you.
I have met two problems when I run test_surface.py. 

(1)ImportError while importing test module 'D:\my_subject\test\freesurfer-surface-master\tests\test_vertex.py'.
Hint: make sure your test modules/packages have valid Python names.
(2)from freesurfer_surface.version import __version__
E   ModuleNotFoundError: No module named 'freesurfer_surface.version'

My anaconda version 3.4，python version 3.6.

**Comment by fphammerle** [comment]
> I'm sorry to bother you.

No problem, thanks for asking!

> (1)ImportError while importing test module 'D:\my_subject\test\freesurfer-surface-master\tests\test_vertex.py'.
> Hint: make sure your test modules/packages have valid Python names.

The modules in `tests` folder are intended to be run with `pytest tests/some_module.py`.
How did you import `test_vertex.py`?

> (2)from freesurfer_surface.version import **version**
> E ModuleNotFoundError: No module named 'freesurfer_surface.version'

The module `version.py` will be created upon installation by a plugin called `setuptools_scm`.
I added a workaround that does not require installation. Could you retry on the current `master` ?
