### ISSUE TITLE
use triangle and vertices to create a graph

### ISSUE THREAD

**Issue by tanjia123456** [fphammerle/freesurfer-surface#26]
I have found two ways to create graph:
 1、use networkx, but this way use vertex and edge, not triangle
 2、use matplotlib.tri.triangulation
So according to the vertices and triangle extracted in lh.white, how to create a graph?
triangle:                                             
0 0 1 3
1 0 3 2
2 0 27 1
3 28 1 27
4 0 2 27
5 31 27 2
6 2 3 4
7 5 4 3
8 2 4 35
9 2 35 31
10 4 5 35

vertices:
0 0 1 3
1 0 3 2
2 0 27 1
3 28 1 27
4 0 2 27
5 31 27 2
6 2 3 4
7 5 4 3
8 2 4 35
9 2 35 31
10 4 5 35

**Comment by fphammerle** [comment]
list all edges:
```python
from freesurfer_surface import Surface

surface = Surface.read_triangular('HLN-12-1.white')

for triangle in surface.triangles:
    for edge_vertex_indices in triangle.adjacent_vertex_indices():
        edge_vertices = surface.select_vertices(edge_vertex_indices)
        print("edge: vertex #{} {} - vertex #{} {}".format(edge_vertex_indices[0],edge_vertices[0], edge_vertex_indices[1], edge_vertices[1]))
```

Sorry, I am not familiar with `matplotlib.tri.triangulation` and `networkx`

**Comment by tanjia123456** [comment]
> 
> 
> list all edges:
> 
> ```python
> from freesurfer_surface import Surface
> 
> surface = Surface.read_triangular('HLN-12-1.white')
> 
> for triangle in surface.triangles:
>     for edge_vertex_indices in triangle.adjacent_vertex_indices():
>         edge_vertices = surface.select_vertices(edge_vertex_indices)
>         print("edge: vertex #{} {} - vertex #{} {}".format(edge_vertex_indices[0],edge_vertices[0], edge_vertex_indices[1], edge_vertices[1]))
> ```
> 
> Sorry, I am not familiar with `matplotlib.tri.triangulation` and `networkx`

thank you! it's waht I want
