### ISSUE TITLE
for label.index, label.hex_color_code, label.name in enumerate(?):

### ISSUE THREAD

**Issue by tanjia123456** [fphammerle/freesurfer-surface#27]
Hello, I'm asking again，I don't konw how to write a annot file to a txt file.
#for label.index, label.hex_color_code, label.name in enumerate(?):

from freesurfer_surface import Annotation

annotation = Annotation.read('rh.aparc.a2009s.annot')
for label in annotation.labels.values():
    with open("rhlabels.txt", "w") as output_file:
        #for label.index, label.hex_color_code, label.name in enumerate(?):
            output_file.write("{} {} {} \n".format(label.index, label.hex_color_code, label.name))
    print(label.index, label.hex_color_code, label.name)

**Comment by tanjia123456** [comment]
by the way , I need to create a feature matrix by surf/rh.sulc. But I found your project not mention it. So do you know how do read it ?

**Comment by fphammerle** [comment]
Hi,

please try:
```python
from freesurfer_surface import Annotation

annotation = Annotation.read("rh.aparc.a2009s.anno")
with open("rhlabels.txt", "w") as output_file:
    for label in annotation.labels.values():
        output_file.write("{} {} {}\n".format(label.index, label.hex_color_code, label.name))
```

**Comment by tanjia123456** [comment]
> 
> 
> Hi,
> 
> please try:
> 
> ```python
> from freesurfer_surface import Annotation
> 
> annotation = Annotation.read("rh.aparc.a2009s.anno")
> with open("rhlabels.txt", "w") as output_file:
>     for label in annotation.labels.values():
>         output_file.write("{} {} {}\n".format(label.index, label.hex_color_code, label.name))
> ```

it's OK. I thought it was the same as the reading vertices method！ So, how to read sulc or thickness file? I'm trying gcn model ,so I nedd to create a feature matrix.

**Comment by fphammerle** [comment]
Sorry, the library is not yet capable to read those formats.

If you want to read `.stats` files, you could try https://github.com/fphammerle/freesurfer-stats#usage

**Comment by tanjia123456** [comment]
what's more, I have created a graph using vertex and triangle by matplotlib. But this graph can't use adjacency_matrix function to create adj_matrix. So, I need some edge to create graph by networkx. Do you know how to extract edge from triangle or other files? I

**Comment by tanjia123456** [comment]
Sorry, I think of another question, I don’t know if you understand it. There are too many vertices extracted from rh.white. I read an article about template to fsaverage5. I tried mri_surf2surf command of freesurfer before, but since rh.white is a coordinate file, it seems that I can’t resample. Do you know how to solve it?

**Comment by fphammerle** [comment]
> Do you know how to extract edge from triangle or other files?

You can use this code to get all edges:
```python
from freesurfer_surface import Surface

surface = Surface.read_triangular('HLN-12-1.white')

for triangle in surface.triangles:
    for edge_vertex_indices in triangle.adjacent_vertex_indices():
        edge_vertices = surface.select_vertices(edge_vertex_indices)
        print("edge: vertex #{} {} - vertex #{} {}".format(edge_vertex_indices[0],edge_vertices[0], edge_vertex_indices[1], edge_vertices[1]))
```

>  I read an article about template to fsaverage5. I tried mri_surf2surf command of freesurfer before, but since rh.white is a coordinate file, it seems that I can’t resample. Do you know how to solve it?

Sorry, I am not familiar with `mri_surf2surf` and `fsaverage5`

**Comment by tanjia123456** [comment]
any way, thank you very much!
