### ISSUE TITLE
extract label information from annotation file

### ISSUE THREAD

**Issue by tanjia123456** [fphammerle/freesurfer-surface#28]
hello, I want to extract   Vertices and corresponding labels.  I use a2009s.annot as label(75 brain regions).  For example there are 5 vertices and 2 labels. I wish to get the label matrix(N*C). N=5 C=2
**vertex1 label1
vertex2 label 2
vertex3  label2
vertex4 label2
vertex5 label1**
what's more, If I need to binary the label matrix，label data will be lost？

**Comment by tanjia123456** [comment]
I tried coding by myself but the output is wrong

`from freesurfer_surface import Surface
from freesurfer_surface import Label
from freesurfer_surface import Annotation

surface = Surface.read_triangular('rh.white')
annotation = Annotation.read('rh.aparc.a2009s.annot')
with open("rhlabels1.txt", "w") as output_file:
    for vertex_index, vertex in enumerate(surface.vertices):
        for label in annotation.labels.values():
            output_file.write("{} {} {} {}\n".format(vertex_index, vertex, label.index, label.name))`

Some output information:
0 [ 16.66563225 -86.72016144 -14.90877438] 0 Unknown
0 [ 16.66563225 -86.72016144 -14.90877438] 1 G_and_S_frontomargin
0 [ 16.66563225 -86.72016144 -14.90877438] 2 G_and_S_occipital_inf
0 [ 16.66563225 -86.72016144 -14.90877438] 3 G_and_S_paracentral
0 [ 16.66563225 -86.72016144 -14.90877438] 4 G_and_S_subcentral
0 [ 16.66563225 -86.72016144 -14.90877438] 5 G_and_S_transv_frontopol
0 [ 16.66563225 -86.72016144 -14.90877438] 6 G_and_S_cingul-Ant
0 [ 16.66563225 -86.72016144 -14.90877438] 7 G_and_S_cingul-Mid-Ant
0 [ 16.66563225 -86.72016144 -14.90877438] 8 G_and_S_cingul-Mid-Post
0 [ 16.66563225 -86.72016144 -14.90877438] 9 G_cingul-Post-dorsal
0 [ 16.66563225 -86.72016144 -14.90877438] 10 G_cingul-Post-ventral
0 [ 16.66563225 -86.72016144 -14.90877438] 11 G_cuneus

**Comment by fphammerle** [comment]
Please try:
```python
surface = Surface.read_triangular('tests/subjects/fabian/surf/lh.pial')
surface.load_annotation_file('tests/subjects/fabian/label/lh.aparc.annot')
for vertex_index, vertex in enumerate(surface.vertices):
    vertex_label_index = surface.annotation.vertex_label_index[vertex_index]
    vertex_label = surface.annotation.labels[vertex_label_index]
    print(vertex_index, vertex, vertex_label)
```

**Comment by tanjia123456** [comment]
Ok I can get what I want! thank you for your reply
