### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by tanjia123456** [fphammerle/freesurfer-surface#29]
hello, Run readvertices.py in other files, sometimes AssertionError appears.
readvertices.py:
`from freesurfer_surface import Surface
surface = Surface.read_triangular("rh.white")
with open("rhvertices.txt", "w") as output_file:
    for vertex_index, vertex in enumerate(surface.vertices):
        output_file.write("{} {}\n".format(vertex_index, vertex))`
Error message：
`Traceback (most recent call last):
  File "F:/free_output/test/test_template/readvertex.py", line 2, in <module>
    surface = Surface.read_triangular("rh.white")
  File "C:\Users\hp\AppData\Roaming\Python\Python36\site-packages\freesurfer_surface\__init__.py", line 364, in read_triangular
    surface._read_triangular(surface_file)
  File "C:\Users\hp\AppData\Roaming\Python\Python36\site-packages\freesurfer_surface\__init__.py", line 332, in _read_triangular
    assert stream.read(3) == self._MAGIC_NUMBER
AssertionError`

do you know how to solve this problem?

**Comment by tanjia123456** [comment]
by the way, Is it possible that I registered rh.white to the fsaverage5 space and used the processed rh.white file? It may be that there is a problem with the generated file

**Comment by fphammerle** [comment]
Hi,

this assertion indicates that the file format is different than expected.

Does this occur for files directly produced by FreeSurfer?
Or only for manually processed/edited files?

**Comment by tanjia123456** [comment]
It was caused by the wrong step of registering to the fsaverage5 space. It has been resolved, thank you
